### ISSUE TITLE
Can't find config.js in Frontend

### ISSUE THREAD

**Issue by ahmedch1** [dzenis-h/Mars-EMS#12]
Hello,
Thanks for your great project but I can't find config.js in frontend exactly in frontend/sr/config/config.js
Can you help me?
thanks in advance

**Comment by BiggaHD** [comment]
@ahmedch1 I've added a config file with instructions. Thank you for your compliment.

**Comment by dzenis-h** [comment]
Problem solved. You shouldn't push your config files to a remote repo, but I think this way I solved the issue for you. Any contributions are welcome.
